package uz.pdp.water_delivery.entity.enums;

public enum TelegramState {
    SHARE_CONTACT, VIEW_PRICE, WAITING, SHARE_LOCATION, CABINET, START_ORDERING, SHARE_REGION, SELECT_BOTTLE_TYPE, SELECT_BOTTLE_NUMBER, CONFIRM_ORDER, CREATE_ORDER, START_DELIVERY, SHARE_START_DELIVERY, ENTER_PASSWORD, ENTER_PASSWORD_DELIVERY, ENTER_PASSWORD_DELIVERY_CONFIRM, ENTER_OLD_PASSWORD_DELIVERY, WAITING_FOR_PHONE, NO_PHONE, CHOOSE_DELIVERY_TIME, CHOOSE_ORDER, GENERATED_LOCATION, SHARE_LOCATION_DELIVERY, START_DELIVERED, DELIVERY_STARTED, SETTING, SAVE_NEW_CONTACT, SAVE_NEW_LOCATION, HAS_ORDER, CHANGE_LOCATION, WAITING_OPERATOR, WAITING_OPERATOR_CHANGE_LOCATION, MY_BASKET, START
}
