CREATE TABLE baskets
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telegram_user_id UUID,
    bottle_type_id   INTEGER,
    amount           INTEGER,
    message_id       INTEGER,
    CONSTRAINT pk_baskets PRIMARY KEY (id)
);

CREATE TABLE bot_constants
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    constant_key   VARCHAR(255)                            NOT NULL,
    constant_value TEXT                                    NOT NULL,
    CONSTRAINT pk_bot_constants PRIMARY KEY (id)
);

CREATE TABLE bottle_types
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            VARCHAR(255),
    description     VARCHAR(512),
    price           INTEGER,
    active          BOOLEAN                                  NOT NULL,
    image           BYTEA,
    image_path      VARCHAR(255),
    order_count     BIGINT,
    is_returnable   BOOLEAN                                  NOT NULL,
    sale_amount     INTEGER,
    sale_discount   INTEGER,
    sale_active     BOOLEAN DEFAULT FALSE                    NOT NULL,
    sale_start_date date,
    sale_end_date   date,
    CONSTRAINT pk_bottletypes PRIMARY KEY (id)
);

CREATE TABLE courier
(
    id             UUID NOT NULL,
    car_type       VARCHAR(255),
    car_number     VARCHAR(255),
    capacity       INTEGER,
    courier_status VARCHAR(255),
    is_active      BOOLEAN,
    user_id        UUID,
    CONSTRAINT pk_courier PRIMARY KEY (id)
);

CREATE TABLE courier_districts
(
    courier_id   UUID NOT NULL,
    districts_id UUID NOT NULL
);

CREATE TABLE current_orders
(
    id           UUID NOT NULL,
    order_id     BIGINT,
    start_time   TIMESTAMP WITHOUT TIME ZONE,
    finish_time  TIMESTAMP WITHOUT TIME ZONE,
    order_count  INTEGER,
    waiting_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_current_orders PRIMARY KEY (id)
);

CREATE TABLE delivery_time
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day        VARCHAR(255),
    start_time time WITHOUT TIME ZONE,
    end_time   time WITHOUT TIME ZONE,
    CONSTRAINT pk_deliverytime PRIMARY KEY (id)
);

CREATE TABLE district
(
    id         UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    CONSTRAINT pk_district PRIMARY KEY (id)
);

CREATE TABLE order_product
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount               INTEGER,
    order_id             BIGINT,
    bottle_types_id      INTEGER,
    bottle_count         INTEGER,
    price_at_purchase    INTEGER,
    discount_at_purchase INTEGER,
    was_on_sale          BOOLEAN,
    CONSTRAINT pk_orderproduct PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id               BIGINT NOT NULL,
    telegram_user_id UUID,
    day              date,
    order_status     VARCHAR(255),
    delivery_time_id INTEGER,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    phone            VARCHAR(255),
    total_price      DOUBLE PRECISION,
    courier_id       UUID,
    region_id        UUID,
    district_id      UUID,
    latitude         FLOAT,
    longitude        FLOAT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE region
(
    id         UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    CONSTRAINT pk_region PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id        INTEGER NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE telegram_user
(
    id                             UUID    NOT NULL,
    created_at                     TIMESTAMP WITHOUT TIME ZONE,
    updated_at                     TIMESTAMP WITHOUT TIME ZONE,
    chat_id                        BIGINT,
    state                          VARCHAR(255),
    user_id                        UUID,
    get_deleting_message           INTEGER,
    region_id                      UUID,
    district_id                    UUID,
    is_home                        BOOLEAN NOT NULL,
    xonadon                        VARCHAR(255),
    podyez                         VARCHAR(255),
    qavat                          VARCHAR(255),
    kv_raqami                      VARCHAR(255),
    password                       VARCHAR(255),
    deleting_message               INTEGER,
    verified                       BOOLEAN,
    address_line                   VARCHAR(255),
    bottle_count                   INTEGER,
    editing_message_id             INTEGER,
    order_count                    INTEGER,
    current_order_count            INTEGER,
    phone_off                      BOOLEAN,
    change_location                BOOLEAN,
    bottle_types_id                INTEGER,
    current_order_delivery_time_id INTEGER,
    current_order_day              date,
    current_order_id               BIGINT,
    editing_current_message_id     INTEGER,
    latitude                       FLOAT,
    longitude                      FLOAT,
    CONSTRAINT pk_telegram_user PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id UUID    NOT NULL
);

CREATE TABLE users
(
    id                UUID NOT NULL,
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    phone             VARCHAR(255),
    password          VARCHAR(255),
    active            BOOLEAN,
    last_bottle_count INTEGER,
    new_user          BOOLEAN,
    paid              BOOLEAN,
    paid_date         date,
    next_month_date   date,
    double_phone      VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE deleting_messages
(
    id         UUID NOT NULL,
    chat_id    BIGINT,
    message    VARCHAR(1000),
    message_id INTEGER,
    CONSTRAINT pk_deleting_messages PRIMARY KEY (id)
);


ALTER TABLE bot_constants
    ADD CONSTRAINT uc_bot_constants_constant_key UNIQUE (constant_key);

ALTER TABLE current_orders
    ADD CONSTRAINT uc_current_orders_order UNIQUE (order_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE baskets
    ADD CONSTRAINT FK_BASKETS_ON_BOTTLETYPE FOREIGN KEY (bottle_type_id) REFERENCES bottle_types (id);

ALTER TABLE baskets
    ADD CONSTRAINT FK_BASKETS_ON_TELEGRAMUSER FOREIGN KEY (telegram_user_id) REFERENCES telegram_user (id);

ALTER TABLE courier
    ADD CONSTRAINT FK_COURIER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE current_orders
    ADD CONSTRAINT FK_CURRENT_ORDERS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDERPRODUCT_ON_BOTTLETYPES FOREIGN KEY (bottle_types_id) REFERENCES bottle_types (id);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDERPRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_COURIER FOREIGN KEY (courier_id) REFERENCES courier (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_DELIVERYTIME FOREIGN KEY (delivery_time_id) REFERENCES delivery_time (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_DISTRICT FOREIGN KEY (district_id) REFERENCES district (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_REGION FOREIGN KEY (region_id) REFERENCES region (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_TELEGRAMUSER FOREIGN KEY (telegram_user_id) REFERENCES telegram_user (id);

ALTER TABLE telegram_user
    ADD CONSTRAINT FK_TELEGRAM_USER_ON_BOTTLETYPES FOREIGN KEY (bottle_types_id) REFERENCES bottle_types (id);

ALTER TABLE telegram_user
    ADD CONSTRAINT FK_TELEGRAM_USER_ON_CURRENTORDERDELIVERYTIME FOREIGN KEY (current_order_delivery_time_id) REFERENCES delivery_time (id);

ALTER TABLE telegram_user
    ADD CONSTRAINT FK_TELEGRAM_USER_ON_DISTRICT FOREIGN KEY (district_id) REFERENCES district (id);

ALTER TABLE telegram_user
    ADD CONSTRAINT FK_TELEGRAM_USER_ON_REGION FOREIGN KEY (region_id) REFERENCES region (id);

ALTER TABLE telegram_user
    ADD CONSTRAINT FK_TELEGRAM_USER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE courier_districts
    ADD CONSTRAINT fk_coudis_on_courier FOREIGN KEY (courier_id) REFERENCES courier (id);

ALTER TABLE courier_districts
    ADD CONSTRAINT fk_coudis_on_district FOREIGN KEY (districts_id) REFERENCES district (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);



insert into roles values (1, 'ROLE_OPERATOR');
insert into roles values (2, 'ROLE_DELIVERY');
insert into roles values (3, 'ROLE_ADMIN');
insert into roles values (4, 'ROLE_USER');
insert into roles values (5, 'ROLE_SUPER_ADMIN');